// angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from './auth.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  user;
  error;

  constructor(private authService: AuthService) {}
  ngOnInit(): void {
    try {
      this.user = this.authService.user.name;
    } catch (error) {
      this.user = null;
    }
  }

  login(user, pass) {
    this.authService.login({user, pass})
      .subscribe(
        res => {
          this.user = res.name;
          this.error = false;
        },
        err => this.error = err.error);
  }

  logout() {
    this.authService.logout();
    this.user = null;
  }

  testApi() {
    this.authService.getResource('friends')
      .subscribe(res => console.log(res.friends), err => console.log(err.error));
    // test API access by invoking getResource on authService.
  }
}

<div class="container">
  <p *ngIf="error" class="error">Login credentials were incorrect!</p>

  <form *ngIf="!user" action="" class="form-group">
    <input type="text" #username id="username">
    <input type="text" #password id="password">
    <button (click)="login(username.value, password.value)">Login</button>
  </form>

  <div *ngIf="user">
    <p> Welcome, {{ user }} </p>
    <button (click)="logout()">Logout</button>
  </div>
  <button (click)="testApi()">Test API</button>
</div>

// react/src/App.js
import React, { Component } from 'react';
import Login from './Login';
import { default as AuthService } from './authService';


class App extends Component {
    state = AuthService.getAuthState();

    componentDidCatch(error, info) {
        console.log(`Component did catch:
        error: ${error},
        info: ${info}`);
    }

    login = (credentials) => {
        AuthService.login(credentials)
            .then(response => {
                this.setState({
                    ...AuthService.getAuthState(),
                    error: undefined
                });
            })
            .catch(err => {
                this.setState({ error: err.error })
            });
    };

    logout = () => {
        AuthService.logout()
            .then(this.setState(AuthService.getAuthState()));
        
    };

    testApi = () => {
        AuthService.getResource('friends')
            .then(res => {
                console.log(res);
                return res;
            })
            .catch(err => {
                this.setState({ error: err.error })
            });
    }

    // ...

    render() {
        const { error, user } = this.state;
        const userDisplay = (user)
            ? <span>User ID: {user.name}</span>
            : null;
        const loginForm = (!user)
            ? <Login onLogin={this.login} />
            : null;
        // const loginForm = user && <Login onLogin={this.login} />
        return (
            <div className="container">
                {/* {(error) ? <Error error={error} /> : null} */}
                {(error) ? <p className="error">{error}</p> : null}
                {loginForm}
                <div className="status">
                    {userDisplay}
                    <button onClick={this.testApi}>Test API</button>
                    <button onClick={this.logout}>Logout</button>
                </div>
            </div>
        );
    }
}

export default App;
